

name: Build 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Builds: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Angular Full CI
        uses: colbyhill21/angular-full-ci/@v1.0
        with:
          repository: AvailabilityServiceChecker/service_checker_client
          path: service_checker_client
          testcommand: run test:ci
          mocha: true
      
