

name: Build 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Builds: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: hgrodriguez91/AvailabilityServiceChecker
          working_directory: service_checker_client
          ref: main
      - name: Angular Full CI
        uses: colbyhill21/angular-full-ci/@v1.0
        with:
          testcommand: run test:ci
          mocha: true
      
