
name: Build 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
           node-version: '14'        
      - run: npm install -g @angular/cli > /dev/null
      - run: cd service_checker_client && npm install
      - run: cd service_checker_client && ng add @angular-eslint/schematics  --skip-confirmation
      - run: cd service_checker_client && npm lint
      - run: cd service_checker_client && npm build
